### ISSUE TITLE
Update improved water source definition

### ISSUE THREAD

**Issue by ernestguevarra** [validmeasures/wash#2]
**From Jonathan (8 November 2017):** 
There has been a change to the ***improved*** water source definitions in the recent update, with *cart with small tank/drum or tanker-truck* and *bottled water* now classed as improved sources without the previous conditions applied (these used to only count as improved in the presence of an improved secondary water source). The workflow is based on the old definitions. For `water1`, `JMPwater2`, `JMPwater3`, `JMPwater4` and `JMPwater5` please revised the code to include *bottled water* and *cart with small tank/drum or tanker-truck* as standard improved water sources which are therefore either limited, basic or safely managed.

**Comment by ernestguevarra** [comment]
This update has been completed with **bottled water and cart with small tank/drum or tanker-truck** added to **improved** water source definition.

**Comment by jon-stokes** [comment]
Thanks @ernestguevarra!
