### ISSUE TITLE
Update definition of "available when needed"

### ISSUE THREAD

**Issue by ernestguevarra** [validmeasures/wash#3]
**From Jonathan (8 November 2017):** 
Based on the latest JMP update (2017), the requirement for *available when needed* for safely managed drinking water definition is 12 hours a day (`water4a`) rather than 24h (`water4b`). Could you please change it?

**Comment by ernestguevarra** [comment]
Available when needed definition updated to 12 hours per day.

**Comment by jon-stokes** [comment]
Many thanks @ernestguevarra for the modifications to line 650 of water indicators workflow
