### ISSUE TITLE
Handwashing data not consistent with JMP definition

### ISSUE THREAD

**Issue by ernestguevarra** [validmeasures/wash#7]
**From Jonathan (8 November 2017):**
Our original question did not ask whether the handwashing station was on premises, therefore based on the 2017 definitions we cannot accurately report on the hygiene ladder. We will be asking this question in future surveys (is handwashing station on premises: yes/no) so we suggest the logic for the JMP hygiene ladder is based on the value of this new response for future surveys (which we are calling `surveydata$san107`) which will be NULL for Dhaka but present for the remaining cities.

**Comment by jon-stokes** [comment]
Ok, understood, thanks @ernestguevarra
