### ISSUE TITLE
Change slum to low-income area

### ISSUE THREAD

**Issue by ernestguevarra** [validmeasures/wash#9]
We discussed the “slum” and “low-income area” terminology before: as you know it’s a bit sensitive to include “slum”, particularly as we want to release the web app on our website. Can you point us to the right parts of the web app code where we can change the label, both for charts and for the “slum/citywide” selector on the top left?

**Comment by ernestguevarra** [comment]
All `slum` terms used for outputting of results (specifically table outputs) have now been changed to `low income area`.

**Comment by jon-stokes** [comment]
Thanks @ernestguevarra
